import json
from io import BytesIO
from datetime import datetime
from typing import Dict, Any, List, Optional

from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

PRIMARY_COLOR = colors.HexColor("#1E3A8A")     # Deep Blue
SECONDARY_COLOR = colors.HexColor("#3B82F6")   # Brand Blue
ACCENT_GREEN = colors.HexColor("#10B981")      # Emerald
ACCENT_RED = colors.HexColor("#EF4444")        # Coral / Red
BG_LIGHT = colors.HexColor("#F8FAFC")          # Light Slate
TEXT_DARK = colors.HexColor("#0F172A")         # Slate 900
TEXT_MUTED = colors.HexColor("#64748B")        # Slate 500
BORDER_COLOR = colors.HexColor("#E2E8F0")      # Slate 200

def _get_custom_styles():
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=PRIMARY_COLOR,
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=TEXT_MUTED,
        spaceAfter=12
    )

    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=PRIMARY_COLOR,
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        "BodyDark",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=TEXT_DARK
    )

    body_muted = ParagraphStyle(
        "BodyMuted",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=TEXT_MUTED
    )

    bullet_style = ParagraphStyle(
        "BulletItem",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=TEXT_DARK,
        leftIndent=12,
        firstLineIndent=-8,
        spaceAfter=4
    )

    return {
        "title": title_style,
        "subtitle": subtitle_style,
        "section": section_heading,
        "body": body_style,
        "muted": body_muted,
        "bullet": bullet_style
    }

def generate_report_pdf(
    report_title: str,
    report_type: str,
    summary: str,
    kpis: Dict[str, Any],
    key_findings: List[str],
    recommendations: List[str],
    created_at: Optional[datetime] = None,
    author: str = "NARASIMHA"
) -> bytes:
    """
    Generates a professional executive PDF report using ReportLab.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = _get_custom_styles()
    story = []

    # 1. Header Banner
    date_str = (created_at or datetime.utcnow()).strftime("%B %d, %Y, %I:%M %p UTC")
    header_data = [
        [
            Paragraph(f"<b>WorkVista</b> &bull; Workforce Analytics", styles["title"]),
            Paragraph(f"<b>Generated By:</b> {author}<br/><b>Date:</b> {date_str}", styles["muted"])
        ]
    ]
    header_table = Table(header_data, colWidths=[360, 180])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(header_table)
    story.append(HRFlowable(width="100%", thickness=1.5, color=SECONDARY_COLOR, spaceBefore=4, spaceAfter=10))

    # 2. Report Meta & Type
    story.append(Paragraph(f"<b>{report_title}</b>", styles["title"]))
    story.append(Paragraph(f"Category: <b>{report_type}</b> &nbsp;|&nbsp; Certified Production Intelligence Audit", styles["subtitle"]))
    story.append(Spacer(1, 4))

    # 3. Executive Summary Card
    story.append(Paragraph("Executive Summary", styles["section"]))
    summary_p = Paragraph(summary, styles["body"])
    summary_box = Table([[summary_p]], colWidths=[540])
    summary_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BG_LIGHT),
        ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(summary_box)
    story.append(Spacer(1, 10))

    # 4. Key Performance Indicators (Grid Table)
    if kpis:
        story.append(Paragraph("Workforce Key Performance Indicators", styles["section"]))
        kpi_items = list(kpis.items())
        kpi_rows = []
        
        # Format 3 KPIs per row
        row = []
        for idx, (k, v) in enumerate(kpi_items):
            cell_content = [
                Paragraph(f"<font color='#64748B'>{k.upper()}</font>", styles["muted"]),
                Spacer(1, 2),
                Paragraph(f"<b><font size=11 color='#1E3A8A'>{v}</font></b>", styles["body"])
            ]
            row.append(cell_content)
            if len(row) == 3:
                kpi_rows.append(row)
                row = []
        if row:
            while len(row) < 3:
                row.append([Paragraph("", styles["body"])])
            kpi_rows.append(row)

        kpi_table = Table(kpi_rows, colWidths=[180, 180, 180])
        kpi_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), BG_LIGHT),
            ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(kpi_table)
        story.append(Spacer(1, 10))

    # 5. Key Findings
    if key_findings:
        story.append(Paragraph("Core Strategic Findings", styles["section"]))
        for item in key_findings:
            bullet = f"&bull; {item}"
            story.append(Paragraph(bullet, styles["bullet"]))
        story.append(Spacer(1, 8))

    # 6. Actionable Recommendations
    if recommendations:
        story.append(Paragraph("Recommended HR Interventions & Next Steps", styles["section"]))
        for idx, item in enumerate(recommendations, 1):
            rec_text = f"<b>{idx}.</b> {item}"
            story.append(Paragraph(rec_text, styles["bullet"]))
        story.append(Spacer(1, 12))

    # 7. Verification & Sign-off Footer
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_COLOR, spaceBefore=10, spaceAfter=8))
    footer_p = Paragraph(
        f"WorkVista HR Intelligence Engine &bull; Analyst: {author} (HR Analytics) &bull; Verified Production Data &bull; Page 1 of 1",
        styles["muted"]
    )
    story.append(footer_p)

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes

def generate_employee_profile_pdf(
    employee_dict: Dict[str, Any],
    prediction_dict: Optional[Dict[str, Any]] = None,
    notes: Optional[List[Dict[str, Any]]] = None,
    tasks: Optional[List[Dict[str, Any]]] = None,
    author: str = "NARASIMHA"
) -> bytes:
    """
    Generates a comprehensive 1-page individual employee profile dossier PDF.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = _get_custom_styles()
    story = []

    # Header
    date_str = datetime.utcnow().strftime("%B %d, %Y")
    header_data = [
        [
            Paragraph(f"<b>WorkVista</b> &bull; Employee Profile Dossier", styles["title"]),
            Paragraph(f"<b>Analyst:</b> {author}<br/><b>Export Date:</b> {date_str}", styles["muted"])
        ]
    ]
    header_table = Table(header_data, colWidths=[360, 180])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(header_table)
    story.append(HRFlowable(width="100%", thickness=1.5, color=SECONDARY_COLOR, spaceBefore=4, spaceAfter=10))

    # Employee Bio Overview
    emp_name = employee_dict.get("employee_name", "Unknown Employee")
    emp_id = employee_dict.get("employee_id", "EMP-0000")
    dept = employee_dict.get("department", "General")
    role = employee_dict.get("role", "Staff")
    current_prod = employee_dict.get("productivity_score", 0.0)
    pred_prod = prediction_dict.get("predicted_productivity", current_prod) if prediction_dict else current_prod
    perf_status = prediction_dict.get("status", "Medium") if prediction_dict else "Medium"
    risk_level = prediction_dict.get("risk_level", "Low") if prediction_dict else "Low"
    risk_score = prediction_dict.get("risk_score", 20.0) if prediction_dict else 20.0

    bio_table_data = [
        [
            Paragraph(f"<b>Name:</b> {emp_name}", styles["body"]),
            Paragraph(f"<b>Employee ID:</b> {emp_id}", styles["body"]),
            Paragraph(f"<b>Department:</b> {dept}", styles["body"])
        ],
        [
            Paragraph(f"<b>Role:</b> {role}", styles["body"]),
            Paragraph(f"<b>Experience:</b> {employee_dict.get('experience', 0)} years", styles["body"]),
            Paragraph(f"<b>Working Hours:</b> {employee_dict.get('working_hours', 40)} hrs/wk", styles["body"])
        ]
    ]
    bio_table = Table(bio_table_data, colWidths=[180, 180, 180])
    bio_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BG_LIGHT),
        ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(bio_table)
    story.append(Spacer(1, 8))

    # Predictive Performance Metrics Grid
    story.append(Paragraph("Productivity & Risk Assessment", styles["section"]))
    metrics_data = [
        [
            Paragraph("<font color='#64748B'>CURRENT PRODUCTIVITY</font><br/><b><font size=12>" + f"{current_prod}%" + "</font></b>", styles["body"]),
            Paragraph("<font color='#64748B'>PREDICTED OUTPUT</font><br/><b><font size=12 color='#1E3A8A'>" + f"{pred_prod}%" + "</font></b>", styles["body"]),
            Paragraph("<font color='#64748B'>PERFORMANCE TIER</font><br/><b><font size=12 color='#10B981'>" + f"{perf_status}" + "</font></b>", styles["body"]),
            Paragraph("<font color='#64748B'>RISK TIER (SCORE)</font><br/><b><font size=12 color='#EF4444'>" + f"{risk_level} ({risk_score})" + "</font></b>", styles["body"])
        ]
    ]
    metrics_table = Table(metrics_data, colWidths=[135, 135, 135, 135])
    metrics_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BG_LIGHT),
        ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(metrics_table)
    story.append(Spacer(1, 8))

    # Behavioral Features Table
    story.append(Paragraph("Observed Behavioral & Operational Features", styles["section"]))
    feat_data = [
        [
            Paragraph(f"<b>Attendance:</b> {employee_dict.get('attendance', 0)}%", styles["body"]),
            Paragraph(f"<b>Workload Index:</b> {employee_dict.get('workload', 0)}", styles["body"]),
            Paragraph(f"<b>Engagement:</b> {employee_dict.get('engagement', 0)}%", styles["body"])
        ],
        [
            Paragraph(f"<b>Skill Proficiency:</b> {employee_dict.get('skill_level', 0)}%", styles["body"]),
            Paragraph(f"<b>Completed Tasks:</b> {employee_dict.get('tasks_completed', 0)}", styles["body"]),
            Paragraph(f"<b>Deadline Adherence:</b> {employee_dict.get('deadline_adherence', 0)}%", styles["body"])
        ]
    ]
    feat_table = Table(feat_data, colWidths=[180, 180, 180])
    feat_table.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(feat_table)
    story.append(Spacer(1, 8))

    # Notes & Interventions (if present)
    if notes:
        story.append(Paragraph(f"HR Operational Notes ({len(notes)} records)", styles["section"]))
        for n in notes[:3]:
            author_tag = n.get("author", "NARASIMHA")
            c_text = n.get("content", "")
            story.append(Paragraph(f"&bull; <i>[{author_tag}]</i>: {c_text}", styles["bullet"]))
        story.append(Spacer(1, 4))

    # Review Tasks (if present)
    if tasks:
        story.append(Paragraph(f"Assigned Review Tasks ({len(tasks)} items)", styles["section"]))
        for t in tasks[:3]:
            title = t.get("title", "")
            t_status = t.get("status", "Pending")
            due = t.get("due_date", "TBD")
            story.append(Paragraph(f"&bull; <b>{title}</b> &mdash; Status: {t_status} (Due: {due})", styles["bullet"]))
        story.append(Spacer(1, 4))

    # Footer
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_COLOR, spaceBefore=4, spaceAfter=6))
    story.append(Paragraph(
        f"WorkVista Employee Dossier &bull; Confidential HR Document &bull; Analyst: {author} &bull; Generated from Database",
        styles["muted"]
    ))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
